### ISSUE TITLE
Texturepacks: connected textures in Angelica

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/Angelica#1134]
### Your GTNH Discord Username

Ngar

### Your Pack Version

Experimental #44

### Your Server

SP 

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Using MISA texture pack, extended version.  

Connected textures should be connected

### The Reality

How it looks like in 2.9.1 (Experimental #44):

<img width="1275" height="1131" alt="Image" src="https://github.com/user-attachments/assets/155d311a-272a-4ef4-81c8-a7ad5cd0f9a8" />

<img width="1020" height="884" alt="Image" src="https://github.com/user-attachments/assets/1d0f89d3-0098-4311-8d1a-8abcbc8882d6" />

### Your Proposal

How it looks like with GTNH version 2.7.4:
![Image](https://github.com/user-attachments/assets/1f4c88c9-6ac8-448c-a15b-f46f3fdbc7bb)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ngar1** [comment]
Shall I test it with other textures or it is a known problem?

**Comment by mitchej123** [comment]
If it's a regression, I'd be more interested in you isolating which version introduced the regression/bug.  That'd be the most helpful for narrowing it down.

**Comment by Ngar1** [comment]
Version 2.8.0 with angelica-1.0.0-beta57.jar has the same problem
Version 2.7.4 with angelica-1.0.0-beta29.jar works well.
I have no pack between to check more

**Comment by PLASMAchicken** [comment]
> Version 2.8.0 with angelica-1.0.0-beta57.jar has the same problem Version 2.7.4 with angelica-1.0.0-beta29.jar works well. I have no pack between to check more

You can manually download the Angelica Versions from https://github.com/GTNewHorizons/Angelica/releases

**Comment by mitchej123** [comment]
I'd do a binary search, pick a version halfway between the two... see if it works or not, you've then eliminated half of the population.  Narrow down which release caused the problem and then we're much closer to finding a solution.

**Comment by qhris** [comment]
This **may** have been fixed in #1132 which was just released in `1.0.0-beta72-pre`.

**Comment by Vexxel** [comment]
Still having issues for me on `1.0.0-beta77-pre`. While textures are correctly connecting in world for me, the blocks in inventories still show as whatever block has metadata:0 for their given blockID in their .properties files. For this frost casing, the solid steel machine casing has meta 0 for example, so all casings past that have the same inventory texture.

<img width="2557" height="1372" alt="Image" src="https://github.com/user-attachments/assets/9df66852-87b1-4a3b-9dec-a6a5449734f2" />

<img width="880" height="176" alt="Image" src="https://github.com/user-attachments/assets/725282f8-73d3-4d88-9180-ebdfab1938e1" />

**Comment by elizabethlfransen** [comment]
I tried updating to ` 1.0.0-beta77pre` and i'm still experiencing these issues. Here are some screenshots

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/32df8aa6-3ee6-4e2e-9aae-c3ef104f3e2c" />

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/c7898db8-ce60-4062-a41a-4bd9a23c0853" />

For context i'm running sphax 64x and complementary shaders

**Comment by Ngar1** [comment]
Problem still in new version angelica-2.0.0-alpha3.jar exist, not solved

**Comment by Ngar1** [comment]
> > Version 2.8.0 with angelica-1.0.0-beta57.jar has the same problem Version 2.7.4 with angelica-1.0.0-beta29.jar works well. I have no pack between to check more
> 
> You can manually download the Angelica Versions from https://github.com/GTNewHorizons/Angelica/releases

because dependencies to other mods with the version, it is not just change and try. Were is a dependence list of each version between?


Version "angelica-1.0.0-beta48.jar" has this failure too
Version "angelica-1.0.0-beta38.jar" has this failure too
can not test beta 32 and beta 35 because it is not compatible with serveral other mods

**Comment by PLASMAchicken** [comment]
Best for testing is to use a minimal sample anyhow. 

Only that one Texture Pack
Only Angelica ( and any other mods you need, but no extras )
Superflat World with only the Blocks that cause Issues, no base or other complicated stuff in the background.

Gives you faster Startup time for Testing, makes sure nothing else in your Pack causes it etc.

**Comment by Ngar1** [comment]
> Best for testing is to use a minimal sample anyhow.
> 
> Only that one Texture Pack Only Angelica ( and any other mods you need, but no extras ) Superflat World with only the Blocks that cause Issues, no base or other complicated stuff in the background.
> 
> Gives you faster Startup time for Testing, makes sure nothing else in your Pack causes it etc.

deleted all other mods and getting an Error from:
lwjgl3ify-2.1.17-forgePatches.jar!META-INF/rfb-plugin/rfb-modern-java.properties

new forge 1.7.10 ends on failure because of missing mixinTweaker
[08:13:36] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker...

It is not so easy as said. There are other mods needed, but I do not know them.

**Comment by Ngar1** [comment]
List of changes, where the failure for textures comes from. Not to many, but I am not able to detect:
https://github.com/GTNewHorizons/Angelica/compare/1.0.0-beta29...1.0.0-beta38

**Comment by MalTeeez** [comment]
Does this still occur?

**Comment by Ngar1** [comment]
Yes, still occure in Exp. 104 (angelica-2.1.16.jar)

<img width="1143" height="901" alt="Image" src="https://github.com/user-attachments/assets/eb26d0b5-b8cc-4a9b-a102-0dd9a2abee35" />

**Comment by Ngar1** [comment]
It is stil not changed in angelica-2.1.42

I am woundering, that Angelica is not able to handle this, which was 7 years ago handled by Optifine, also with random textures for stone.

**Comment by MalTeeez** [comment]
> It is stil not changed in angelica-2.1.42
> 
> I am woundering, that Angelica is not able to handle this, which was 7 years ago handled by Optifine, also with random textures for stone.

We'll close this issue once it is implemented, but its hardly a high priority. You are also free to contribute or switch to optifine, if you cannot handle playing with this feature.

**Comment by Ngar1** [comment]
GTNH is not compatible to Opifine anymore (since 2 y?), thats why I had to switch to Angelica. I open in past an issue about that and the answer was:use Angelica, it is better than optifine...

**Comment by Ngar1** [comment]
Still not solved in Beta 2 of 2.9.0
with angelica-2.1.50.jar
and tested with angelica-2.1.53.jar - not solved
