### ISSUE TITLE
GTNH: Holo Glasses jitter

### ISSUE THREAD

**Issue by AmateriaLinkingBook** [GTNewHorizons/Angelica#413]
### Your GTNH Discord Username

amaterialinkingbook

### Mod Version

angelica-1.0.0-alpha35 (GTNH 2.6.0-beta-2)

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

See this video:

[2024-04-06 00-27-34.webm](https://github.com/GTNewHorizons/Angelica/assets/57226849/d83d8cd8-4bea-45f7-9eef-54715cfb36f6)

Visible jittering of the Holo-HUD which previously (GTNH 2.5) was not there. Happens on all inventories in my base.
Gets fixed when setting config/angelica-modules.cfg --> enableHudCaching=false (enabled by default)
Maybe this was an oversight?

### Mod List or GTNH Pack Version

GTNH 2.6.0-beta-2
(Windows, Java 17.0.8.101 by Eclipse Adoptium, standard java args from DreamMasters announcement link of this beta)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by AmateriaLinkingBook** [comment]
well I have no idea how this is implemented but if this goes on a sort of HUD-fast-render-whitelist I think it is good to mention.

**Comment by Wacchi-Lorie** [comment]
> Known issue, same thing affects Xaero's waypoints

better use xaero, xaxa

**Comment by Caedis** [comment]
Xaero's should now be fixed when #418 is merged.

Looking at holoinventory now

**Comment by JuliaScythe** [comment]
Hi, the jittering still occurs for me on alpha39 (and no other changed mods from the latest GTNH beta), regardless of the HUD caching setting.

Java 21.0.3 / GPU: AMD Radeon RX 5700

**Comment by JuliaScythe** [comment]
Ah never mind, it fixed itself after a while - presumably a shader caching issue or something.

**Comment by Caedis** [comment]
shader?

**Comment by JuliaScythe** [comment]
Oh, I don't mean any minecraft shaders (I'm not using any, to be clear) -- anyway I think I was mistaken above and the problem still occurs, but only when I'm moving, it's smooth when standing still.

**Comment by AmateriaLinkingBook** [comment]
I also still have this Problem in beta 3 where it would be fixed if standing still but just moving the camera, yet still jitter when moving the player.

**Comment by Caedis** [comment]
You both need to also update HoloInventory
https://github.com/GTNewHorizons/HoloInventory/releases/tag/2.4.4-GTNH

**Comment by Wacchi-Lorie** [comment]
> You both need to also update HoloInventory https://github.com/GTNewHorizons/HoloInventory/releases/tag/2.4.4-GTNH

tested with 2.4.4 hologlass, issue still exists. along with [this one](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15936), i think this is related cuz both lag occur with newer angelica version with newer modpack version( i'm using 2.6.0-beta3 with some mods updated to latest)

**Comment by Caedis** [comment]
I can't replicate it

**Comment by Wacchi-Lorie** [comment]
> I can't replicate it


https://github.com/GTNewHorizons/Angelica/assets/57549294/0f4ba2aa-d4c9-4c99-99b4-2746a7f077a6

herez my situation. and my [client modlist](https://github.com/GTNewHorizons/Angelica/files/15140602/sys.info.txt) and [server modlist](https://github.com/GTNewHorizons/Angelica/files/15140616/server.info.txt)
dunno if it helps, issue exist for me though, im at 2.6.0-beta3 for sure
