### ISSUE TITLE
Sildurs Vibrant Shader: The probably last few issues

### ISSUE THREAD

**Issue by Pilzinsel64** [GTNewHorizons/Angelica#833]
### Your GTNH Discord Username

Pilzinsel64 (pilzinsel64)

### Mod Version

1.0.0-beta28

### Bug Report

Thanks to all your hard work, the Sildurs Vibrant Shader has actually become *usable*. I still wont prefer to switch because some minor issues remaining, but it's not far away anymore. As I am not able to help developing directly, I just can help getting you into the issues with simple bug reports, as you told me. Yet bundeled into one issue, just tell me to make separate issues for and I will do. But I think that issue 1 and two might have the same reason.

Just want to mentoin that I didn't any changes to configs. I just installed two fresh Minecraft instances and dropped in the mods and shader packs, without changing any config, also not in-game.

### 1.7.10

![clouds](https://github.com/user-attachments/assets/0ccf808a-2f94-4510-96b0-171dd92ea721)

### 1.21.4

![clouds](https://github.com/user-attachments/assets/e2cb4c63-8431-4e04-ba19-8a2fd897f703)

## Issue 2: Water looks weird

Might have something todo with issue 1 but let's list it separately.

### 1.7.10

![water1](https://github.com/user-attachments/assets/c0ca628b-fefb-4629-995d-b1f82eb55f2d)
![water2](https://github.com/user-attachments/assets/a6b68cd1-acd4-4adf-8c16-01c0c2c796a9)
![water3](https://github.com/user-attachments/assets/20a17ceb-34d0-4113-bec5-c253e8fc1fd9)

### 1.21.4

![water](https://github.com/user-attachments/assets/0d3b532b-9633-4e71-b51f-fb35bcf26866)

## Issue 3: Anti-Aliasing

**Please not that v1.51 is used here as v1.52 has anti-aliasing disabled due an issue report from me. See https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/209** However, if we (so you) get it fixed on Angelica side (via v1.51) the Sildur dev can enable it back on.

For some reason, looks ugly when moving around. However, on modern versions it works fine. V1.29 is the last version that have working anti-aliasing but saldy this version has an issue on both, Iris and Angelica, that prvents me from testing it accurately.

### 1.7.10

https://cloud.pilzinsel64.de/s/r4iXFEH4CKB8G7G

### 1.21.4

https://cloud.pilzinsel64.de/s/JWjXnXn7pDeNp2X

## Other issues

There are a few other issues that are hard to track down right now.

## Logs

Here are the logs of both versions. I enabled verbose logging. Maybe you can see any other issues here.

### 1.7.10

[latest.log](https://github.com/user-attachments/files/18309786/latest.log)
[fml-client-latest.log](https://github.com/user-attachments/files/18309785/fml-client-latest.log)

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

## 1.7.10 (Forge)

![1 7 10](https://github.com/user-attachments/assets/b96c9e1c-c31a-4536-9e15-e9336b41a5a1)

## 1.21.4 (Fabric)

![1 21 4](https://github.com/user-attachments/assets/f203d371-03c3-4156-a567-ce122b6d10e8)

## Shaderpacks

Mostly v1.52, but compared sometimes to 1.29.
![grafik](https://github.com/user-attachments/assets/2b8b7617-65b1-4231-83d9-1bff02d55f47)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by AdotBdot** [comment]
I have the same issue. It seems to happen not only with Sildurs shaders but probably with any shaders. It might be some performance fix that causes this but I cannot figure out what exactly.

**Comment by Cleptomania** [comment]
If someone could do an updated test of these issues with Angelica beta40, that would be great. We backported a feature from more modern Iris that fixed a lot of small shader incompatibilities, so it might have addressed some of these.

**Comment by Pilzinsel64** [comment]
@Cleptomania I've tested it with beta 40 recently as I had the hope that exactly this feature helps, but saldy no. Allt three issues here persist in beta 40. And it doesn't seem like toggling any option in the settings UI changes anything. :/

**Comment by valentimarco** [comment]
gtnh 2.7.4 gives this warning when trying to load the shaders:
```log
[22:51:52] [Client thread/INFO] [AngelicaShaders]: Destroying pipeline OVERWORLD
[22:51:52] [Client thread/WARN] [AngelicaShaders]: Tried to get boolean value for unknown option: Shadows || Volumetric_Lighting, defaulting to true!
[22:51:52] [Client thread/INFO] [AngelicaShaders]: Profile: Custom (+11 options changed by user)
[22:51:52] [Client thread/INFO] [AngelicaShaders]: Using shaderpack: Sildur's Vibrant Shaders v1.53 Extreme.zip
[22:51:52] [Client thread/INFO] [AngelicaShaders]: Creating pipeline for dimension OVERWORLD
[22:51:52] [Client thread/INFO] [ChunkBuilder]: Stopping worker threads
[22:51:52] [Client thread/INFO] [ChunkBuilder]: Started 6 worker threads
[22:51:52] [Client thread/WARN] [AngelicaShaders]: A shader appears to require the lightmap texture matrix even after transformations have occurred
[22:51:52] [Client thread/WARN] [AngelicaShaders]: Iris handles this correctly but it indicates that the shader is doing weird things with lightmap coordinates
```

**Comment by Caspianlake** [comment]
> If someone could do an updated test of these issues with Angelica beta40, that would be great. We backported a feature from more modern Iris that fixed a lot of small shader incompatibilities, so it might have addressed some of these.

Tested with Beta60, GTNH 2.8.1 and Sildurs Shaders. The issue persists. There is also an issue with bloom but that may be Sildur's related.

**Comment by Pilzinsel64** [comment]
Let me give a quick update, based on beta 68.

## Fixed

- Anti-aliasing (TAA) is working great now! ([requested](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/390) to re-enable this for v1.52+ in Sildurs)

## Open

- Sky & water texture (probably the same issue)

**Comment by MalTeeez** [comment]
Can't test this due to #1288, but I would assume the issue is still present on latest.

**Comment by Pilzinsel64** [comment]
Anti aliasing is fixed, but water and sky are still broken (alpha 8 and previous). Also, transculent textures are broken for Sildurs in general since 2.0, see #1244

**Comment by Pilzinsel64** [comment]
Fixed. Used latest angelica + latest Sildurs for testing.
<img width="1920" height="1008" alt="Image" src="https://github.com/user-attachments/assets/e6dcddec-edd8-49b6-b049-92e665f028bf" />
